version: '3.9'
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - '5444:5444'
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres
    env_file: .env
    ports:
      - '5430:5432'
